### PR TITLE
Image: added copyMergeAlpha().

### PR DESCRIPTION
**Pull request by radekdostal**
Merge two true colour images with variable opacity while maintaining alpha transparency of both images.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
:-1: Too much code for too narrow use-case.

**Comment by radekdostal** [comment]
I think it isn't narrow use-case. Merging images by method place() produces black background where two pixels with transparency from each image are covered. This new method copyMergeAlpha() produces correctly image (green map on the top with 50% transparency).

example

**Comment by enumag** [comment]
In that case maybe this method should replace the original place method.

**Comment by radekdostal** [comment]
The dark side of this method is its slowness, because iterating through all pixels. I think, that it has specific use only for images with transparency, so replace the place() method is not a good idea.

**Comment by enumag** [comment]
In that case can you try finding out if the place method can be fixed (without pixel iteration)? I mean there should be same cases of this on the internet.

**Comment by radekdostal** [comment]
I was unable to find a solution without pixel iteration. Moreover, the method signature is not compatible with place() method, because it allows to use even a fragment of the picture.

**Comment by radekdostal** [comment]
It is a [PHP bug](https://bugs.php.net/bug.php?id=23815). There is an opened [pull request](https://github.com/php/php-src/pull/211) with the same algorithm as I took. So I think that only solution is algorithm with pixel iteration.

**Comment by dg** [comment]
This implementation is extreme slow, method has unclear name and a lot of parameters and gives a very different results for opacity = 0 and opacity = 1.

**Pull request closed without merging**
