### PR TITLE
Removed the \t char for 4 spaces.

### PR DESCRIPTION
**Pull request by tiagosampaio**
- bug fix? no   
- new feature? no
- BC break? no

Replaced the \t character for 4 spaces by default. It's not a good practice to use tabs on indentation.

### CODE REVIEW

**Comment by dg** [comment]
I prefer 3 spaces. Why four?

**Comment by milo** [comment]
Sorry, but three or four spaces is nonsence. The best practice is 7.

**Comment by dg** [comment]
It is true that 7 is my lucky number… I'm confused, because I really prefer three spaces.

Solution may be third parameter, where everybody can pass the string with how many spaces he wants. Default value can be tab, because it is always one. @tiagosampaio, what do you think?

**Comment by tiagosampaio** [comment]
@dg I think it's a great idea to create a new parameter for that reason. It solves the problem (and preferences) of us all :D

**Comment by tiagosampaio** [comment]
@milo Really? 7 spaces for each indentation? You've got to implement and follow the object calisthenics principles straightforwardly for every piece of code you create or you have to change the code standard to use 250 columns... I'm just kidding bro. :D

**Comment by dg** [comment]
@tiagosampaio maybe this will help you https://github.com/nette/php-generator#tabs-versus-spaces

**Comment by tiagosampaio** [comment]
Thanks @dg! I think it will help me.

**Pull request closed without merging**
