### PR TITLE
WIP: Json: it should be now clear what is a workaround for what problem and PHP version

### PR DESCRIPTION
**Pull request by JanTvrdik**
Note to self: use `phpversion("json")`

### CODE REVIEW

**Comment by dg** [comment]
@JanTvrdik  is it still valid?

**Comment by JanTvrdik** [comment]
Yes, it's more valid now then before, actually.

**Comment by dg** [comment]
So can you rebase it of something?

**Comment by dg** [comment]
Ping @JanTvrdik

**Comment by JanTvrdik** [comment]
Rebasing the current code is useless, it needs to be rewritten to take `phpversion("json")` into consideration because there are now there available implementations – json, jsonc a jsond.

**Comment by dg** [comment]
Should I close it or do you want to finish it?

**Comment by JanTvrdik** [comment]
I would like to finish this.

**Comment by dg** [comment]
@JanTvrdik it is already finished, yes?

**Comment by JanTvrdik** [comment]
Yes, it is!

**Pull request closed without merging**
