### PR TITLE
Strings: replacePrefix() and replaceSuffix()  methods added

### PR DESCRIPTION
**Pull request by Northys**

### CODE REVIEW

**Comment by Northys** [comment]
ping @dg

**Comment by dg** [comment]
I am not sure that these functions are too usefull.

**Comment by Northys** [comment]
@dg maybe you don't use these methods every day but its nice to have them

**Comment by Northys** [comment]
@dg you can close this PR if you don't want these methods

**Comment by dg** [comment]
OK

**Pull request closed without merging**
