### PR TITLE
Callback: workaround for Suhosin extension

### PR DESCRIPTION
**Pull request by radekdostal**
- bug fix? yes
- new feature? no
- BC break? no

Workaround for segmentation fault with enabled Suhosin extension.
https://github.com/sektioneins/suhosin/issues/114
Successfully tested on production server.

Related to https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc?p=4#p184788

### CODE REVIEW

**Comment by radekdostal** [comment]
ping @dg

**Comment by dg** [comment]
Is it related only to PHP 5.6?

**Comment by radekdostal** [comment]
Stable version of [Suhosin](https://suhosin.org/stories/download.html) is available only for PHP 5.x. @milo can you test [this issue](https://github.com/sektioneins/suhosin/issues/114) for PHP 7 with development version of Suhosin, please?

**Comment by dg** [comment]
It's OK, workaround for dev-version is not needed.

**Pull request merged**
