### PR TITLE
Added missing reflection types

### PR DESCRIPTION
**Pull request by mabar**
- bug fix / new feature? both, I guess
- BC break? no

### CODE REVIEW

**Comment by dg** [comment]
PHP reflection methods never returns `static` or `$this`

**Comment by mabar** [comment]
I got Foo\Bar\mixed for class Foo\Bar\Baz class ([here](https://github.com/nette/schema/blob/v1.0.0/src/Schema/Helpers.php#L65)) so I expected that any type from phpdoc is also possible. I will write some tests for it

**Comment by dg** [comment]
Oh, my comment was related to method `normalizeType()`, I did not notice `expandClassName()`.

**Comment by mabar** [comment]
So should I make it expandClassName() only?
I accidentally commited .idea files, sorry for mess

**Comment by dg** [comment]
I think the problem you are solving is in Schema, not in class Reflection. It is strictly related to the PHP (not to the phpDoc), so `mixed` for example is not built-in type and `$this` is not class name.

**Pull request closed without merging**
