### PR TITLE
Destroy resource if Image is destroyed [WIP]

### PR DESCRIPTION
**Pull request by bckp**
If you do not destroy image with imagedestroy, resource will be allocated for the rest of script life, this is problem in CLI scripts

- bug fix? yes
- new feature? no
- BC break? yes

This is mostly problem for CLI based scripts, that work with Nette\Utils\Images, if you save the image and unset variable, imagedestroy is not called and image stay in memory to the end of script life, it is fine if you load few images, but if you load more then few (10+) you can exhausted memory limit easily.

### CODE REVIEW

**Comment by bckp** [comment]
Ummm, do not understand why tests fail :/

**Comment by dg** [comment]
Because it is BC break.

**Comment by bckp** [comment]
Yeah, I was testing master instead of my branche, this is why I was confused.

**Comment by dg** [comment]
I don't understand why PHP doesn't release resource automatically? It should be reported as PHP bug.

**Comment by dg** [comment]
closing due to human timeout

**Pull request closed without merging**
