### PR TITLE
Image::place preserves alpha channel

### PR DESCRIPTION
**Pull request by dg**
Related to https://github.com/nette/utils/pull/90

### CODE REVIEW

**Comment by radekdostal** [comment]
@dg Your solution is amazing!
For example: two images 620x385px
With 4fcb6e777fc095714cb63fcbf047a750fddcaa51 my script runs about one second.
With abfcf392b2f3f64c7c6dacb57857e7064ff77d0e even just half a second.
(With #90 the script runs about 17 seconds).

**Comment by enumag** [comment]
@dg Awesome!

**Comment by dg** [comment]
It is still order of magnitudes slower than imagecopymerge for images without alpha. And I don't know how to detect whether alpha is used or not.

**Comment by radekdostal** [comment]
Maybe http://php.net/manual/en/function.getimagesize.php#105033.

**Comment by dg** [comment]
It is not about files, but about GD images in memory.

**Comment by radekdostal** [comment]
What about php://memory wrapper?
In [this code](https://code.google.com/p/inspired-social/source/browse/trunk/plugin/wp-content/plugins/article2pdf/contributed/fpdf/fpdf_alpha.php?r=10#202) exists method _parsepng() which parses PNG header.

**Pull request merged**
