### PR TITLE
Srings::toAscii() converts degree sign to ^

### PR DESCRIPTION
**Pull request by lm**
Degree sign ° is now incorrectly converted to `0xB0`.

### CODE REVIEW

**Comment by fprochazka** [comment]
:+1: this broke some of our CSV exports, because the sign was not properly handled.

**Comment by JanTvrdik** [comment]
@fprochazka Why do you thing that it was not properly handled?

**Comment by JanTvrdik** [comment]
Could anyone explain to me why and under what circumstances was `\xC2\xB0` encoded to `xB0`?

**Comment by fprochazka** [comment]
It was a system library issue

> S libiconv je vystup:
> string(2) "^0”
> 
> S glibc:
> string(1) “?"

**Comment by lm** [comment]
On servers with iconv via glibc, iconv(…, CP1250) causes this.

**Comment by JanTvrdik** [comment]
Ok. Are we sure that this is the only character affected? Or are there possibly others?

**Comment by fprochazka** [comment]
We're not. We've only fixed the one that was bothering us :)

**Comment by JanTvrdik** [comment]
I tried:

~~~php
for ($code = 0x0000; $code <= 0x10FFFF; $code++) {
	if ($code % 0x1000 === 0) printf("U+%06X\n", $code);
	$utf8 = iconv('UTF-32BE', 'UTF-8//IGNORE', pack('N', $code));
	$ascii = Nette\Utils\Strings::toAscii($utf8);
	if (!preg_match('#^[\x00-\x7F]*+\z#', $ascii)) {
		printf("U+%06X: %s -> %s\n", $code, bin2hex($utf8), bin2hex($ascii));
	}
}
~~~

with the following result:
~~~
U+0000A4: c2a4 -> a4
U+0000A6: c2a6 -> a6
U+0000A8: c2a8 -> a8
U+0000AC: c2ac -> ac
U+0000B0: c2b0 -> b0
U+0000B1: c2b1 -> b1
U+0000B4: c2b4 -> b4
U+0000B5: c2b5 -> b5
U+0000B6: c2b6 -> b6
U+0000B7: c2b7 -> b7
U+0000B8: c2b8 -> b8
U+0002B9: cab9 -> b4
U+0002BA: caba -> b4b4
U+0002BB: cabb -> 91
U+0002BC: cabc -> 92
U+0002C7: cb87 -> a1
U+0002CA: cb8a -> b4
U+0002D8: cb98 -> a2
U+0002D9: cb99 -> ff
U+0002DB: cb9b -> b2
U+0002DD: cb9d -> bd
U+000374: cdb4 -> b4
U+000387: ce87 -> b7
U+00044A: d18a -> b4b4
U+00044C: d18c -> b4
U+000539: d4b9 -> 5491
U+000549: d589 -> 4391
U+000551: d591 -> 4391
U+000553: d593 -> 5091
U+000554: d594 -> 4b91
U+000569: d5a9 -> 7491
U+000579: d5b9 -> 6391
U+000581: d681 -> 6391
U+000583: d683 -> 7091
U+000584: d684 -> 6b91
U+0005D0: d790 -> 92
U+0005E2: d7a2 -> 91
U+000E05: e0b885 -> 6bb468
U+000E12: e0b892 -> 74b468
U+000E29: e0b8a9 -> 73b4
U+000E2F: e0b8af -> 87
U+0010D9: e18399 -> 6b92
U+0010DE: e1839e -> 7092
U+0010E2: e183a2 -> 7492
U+0010E7: e183a7 -> 7192
U+0010EC: e183ac -> 747392
U+0010ED: e183ad -> 636892
U+002020: e280a0 -> 86
U+002021: e280a1 -> 87
U+002022: e280a2 -> 95
U+002030: e280b0 -> 89
U+002034: e280b4 -> b4b4b4
U+002057: e28197 -> b4b4b4b4
U+0020AC: e282ac -> 80
U+002103: e28483 -> b043
U+002109: e28489 -> b046
U+002122: e284a2 -> 99
U+002219: e28899 -> 95
U+0022C5: e28b85 -> b7
U+0022EF: e28baf -> b7b7b7
U+00FB20: efaca0 -> 91
U+00FB21: efaca1 -> 92
U+00FB2E: efacae -> 9261
U+00FB2F: efacaf -> 9261
U+00FB4F: efad8f -> 926c
U+00FFE2: efbfa2 -> ac
U+00FFE4: efbfa4 -> a6
~~~

**Comment by JanTvrdik** [comment]
The easy fix is obviously to do:
~~~php
$s = preg_replace('#[^\x00-\x7F]*+#', '', $s);
~~~

But maybe some characters are worth handling them manually.

**Comment by dg** [comment]
Fixed

**Pull request merged**
