### PR TITLE
Arrays: added wrap() method

### PR DESCRIPTION
**Pull request by milo**
- new feature
- BC break? no
- doc PR: will

I'm using such conctruction quite often, maybe I'm not the only one.

### CODE REVIEW

**Comment by milo** [comment]
Maybe implement it by
```php
count($arr) ? ($prefix . implode($suffix . $glue . $prefix, $arr) . $suffix) : '';
```
but crucial is an API. No need for array count condition and prefix/suffix on single place.

**Comment by dg** [comment]
What about method `wrap($arr, $prefix, $suffix)`? And than combine `implode` with `wrap`?

**Comment by milo** [comment]
Sure, `wrap()` is better approach. Updated.

Not sure about type casting everything to string.

**Comment by dg** [comment]
Great

**Comment by milo** [comment]
Thank you!

**Pull request merged**
