### PR TITLE
Html::setText: encode quotes too

### PR DESCRIPTION
**Pull request by CZechBoY**
- bug fix
- BC break? yes

Hi,
first of all one question: Why was encoding of quotes skipped?

### CODE REVIEW

**Comment by dg** [comment]
Because it is not needed in HTML text.

**Comment by CZechBoY** [comment]
But it is needed when it is used in html attributes. Or is there any other way to create html parameter escaped text?

**Comment by dg** [comment]
See documentation how to use Nette\Utils\Html

**Comment by dg** [comment]
See documentation how to use Nette\Utils\Html

**Comment by CZechBoY** [comment]
There is no mention to not use in html attributes, and there is no mention to use only in html body.

**Comment by dg** [comment]
https://doc.nette.org/cs/2.4/html-elements#toc-obsah-elementu

**Comment by CZechBoY** [comment]
So you mean I should create Html element with attribute containing another Html instance?
In my case I have Latte template which has element with attribute containing problematic Html instance.

**Comment by dg** [comment]
I don't understand what you mean. setText() and setHtml() have nothing to do with attributes.

**Comment by dg** [comment]
I'm not here to guess what Adam meant.

**Comment by JanTvrdik** [comment]
> I'm not here to guess what Adam meant.

Is a viable approach for normal issues. It's not viable approach for security-related issues.

**Comment by dg** [comment]
See https://github.com/nette/utils/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by CZechBoY** [comment]
Sorry, I did not read those issue templates, possibly because I craeted pull request instead of issue.

Ok here is example with working code.
```php
https://github.com/CZechBoY/html-parameter-xss/blob/master/test.php
```

**Comment by dg** [comment]
Html is not supposed to be used this way.

**Comment by JanTvrdik** [comment]
@CZechBoY You previously mentioned Latte, but the test does not use Latte. Can you post an example with Latte where you've encountered this problem?

**Comment by CZechBoY** [comment]
@dg Then special chars will be double escaped, quotes only once.
@JanTvrdik I realized that it affects only version 2.3. Version 2.4 has context for html attributes.

**Comment by JanTvrdik** [comment]
> Nowhere is mentioned that this is a security issue.

Should in the future sentence such as „escaping is a concept directly related to security“ or „wrong escaping is an indication of possible security issue“ be included? The user (in general) may very well not understand escaping well enough to know what is and what is not a security issue. Please be more careful in the future when closing security-related issues / pull requests. This issue just happened to be fixed in Latte 2.4, the next one may not be.

**Comment by dg** [comment]
Be so kind and do not teach me how to deal with issues.

**Pull request closed without merging**
