### PR TITLE
Add getIntlDateFormat method in Datetime class

### PR DESCRIPTION
**Pull request by petrparolek**
- new feature? yes
- BC break? no
- doc PR: nette/docs# I can prepare if PR will be merged

In Nette Utils I didn't find method which I could replace deprecated PHP function `strftime('%B', $datetime->getTimestamp()),` which I used to Czech translation of munth.

I found solution at https://stackoverflow.com/a/46275845/6346869

### CODE REVIEW

**Comment by petrparolek** [comment]
here are formats https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table

**Comment by stepapo** [comment]
For me this would be useful, but why is it static and not like `return $formatter->format($this);`?

**Comment by JanTvrdik** [comment]
Instead of 

~~~php
echo Nette\Utils\DateTime::getIntlDateFormat(
	format: 'LLLL YYYY HH:mm:ss',
	time: new DateTimeImmutable('2021-02-01 15:47:21'),
	locale: 'cs_CZ',
	timeZone: 'Europe/Prague'
)
~~~

you can just use

~~~php
echo IntlDateFormatter::formatObject(
    datetime: new DateTimeImmutable('2021-02-01 15:47:21', new DateTimeZone('Europe/Prague')),
    format: 'LLLL YYYY HH:mm:ss',
    locale: 'cs_CZ',
);
~~~

**Comment by petrparolek** [comment]
> For me this would be useful, but why is it static and not like `return $formatter->format($this);`?

thanks

**Comment by dg** [comment]
I think it's better to use IntlDateFormatter::formatObject

**Comment by petrparolek** [comment]
thanks @dg and @JanTvrdik for solution

**Pull request closed without merging**
